from enum import IntEnum


class AgentType(IntEnum):
    NONE = 0
    TEST = 1
    ACTIVE_INFERENCE_RELATIVE_CONTROL = 2
    ACTIVE_INFERENCE_ABSOLUTE_CONTROL = 3
    HEURISTIC = 4
    ACTIVE_INFERENCE_EXPERIMENTAL_1 = 5
