from enum import Enum


class AgentType(Enum):
    NONE = 0
    TEST = 1
    ACTIVE_INFERENCE = 2
    REINFORCEMENT_LEARNING = 3
    HEURISTIC = 4
    ACTIVE_INFERENCE_EXPERIMENTAL_1 = 5
    ACTIVE_INFERENCE_EXPERIMENTAL_2 = 5
